site:
  title: Trento Documentation
  url: https://trento-project.github.io/docs
  start_page: ROOT::index.adoc

content:
  sources:
    - url: ./../
      start_path: trento-docs-site
      branches: [HEAD, latest]

ui:
  bundle:
    url: ./../trento-docs-site-ui/build/ui-bundle.zip
    snapshot: true

output:
  dir: ./build/trento-docs-site-public

antora:
  extensions:
  - '@antora/collector-extension'
  - require: '@sntke/antora-mermaid-extension'
    mermaid_library_url: /_/js/vendor/mermaid/mermaid.esm.min.mjs
    script_stem: header-scripts
    mermaid_initialize_options:
      start_on_load: true
  - require: '@antora/lunr-extension'
    index_latest_only: true

asciidoc:
  attributes:
    page-pagination: ''
    site-gen-antora: ''
    imagesdir: _images
